[package]
name = "tiny-oom"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
procfs = "0.12.0"
simple_logger = { version = "2.1.0", features = ["colors", "timestamps"] }
